const products = {
  shoes: [
    {
      id: 1,
      name: "Nike Mercurial Superfly",
      slug: "nike-mercurial-superfly",
      image: "/nike-mercury.jpg",
      rating: 4.5,
      category: "football",
      price: 1999,
      desc: "High-performance football boots designed for explosive speed and precision control.",
    },
    {
      id: 2,
      name: "Sega Winner",
      slug: "sega-winner",
      image: "/sega-winner.jpg",
      rating: 4.1,
      category: "basketball",
      price: 680,
      desc: "The Sega Winner Football Shoes offer you top-notch performance on any ground. These shoes are made with an upper shell of water-resistant synthetic, and a sole consisting of a TPU material that is ideal for both hard and turf grounds.",
    },
    {
      id: 3,
      name: "Nike LeBron Witness 7",
      slug: "nike-lebron-witness-7",
      image: "/nike-lebron.jpg",
      rating: 4.3,
      category: "basketball",
      price: 4999,
      desc: "Built for explosive performance and durability, designed to support power players.",
    },
    {
      id: 4,
      name: "Strike 1912",
      slug: "Strike-1912",
      image: "/strike-1912-tennis1.jpg",
      rating: 4.8,
      category: "tennis",
      price: 1999,
      desc: "Comfortable Tennis Badminton Sports Shoe For Men's",
    },
    {
      id: 5,
      name: "Boldfit Badminton Shoes",
      slug: "boldfit-badminton-shoes",
      image: "/boldfit-shuttle.jpg",
      rating: 4.5,
      category: "shuttle",
      price: 999,
      desc: "Breathable Non Marking Shoes for Badminton",
    },
    {
      id: 6,
      name: "Puma 22 FH",
      slug: "puma-22-fh",
      image: "/puma-cricket.jpg",
      rating: 4.6,
      category: "running",
      price: 4549.0,
      desc: "Experience unrivaled performance and style with Puma 22 FH Rubber VK Cricket Shoes",
    },
    {
      id: 7,
      name: "Nivia Encounter",
      slug: "nivia-encounter",
      image: "/nivia-encounter.jpg",
      rating: 4.4,
      category: "football",
      price: 749,
      desc: "Premolded heel counter for protection and secure heel fit, Die-cut light weight Polyester cloth EVA insole Football boots"
    },
    {
      id: 8,
      name: "Nivia Sterling",
      slug: "nivia-sterling",
      image: "/nivia.jpg",
      rating: 4.7,
      category: "football",
      price: 2810,
      desc: "Stability running shoes designed for controlled motion and reliable comfort.",
    },
  ],
  balls: [
    {
      id: 9,
      name: "Nivia Football",
      slug: "nivia-football",
      image: "/balls/nivia-football.jpg",
      rating: 4.7,
      category: "football",
      price: 999,
      desc: "Suitable For: All Conditions | Ideal For: Training/Match",
    },
     {
      id: 10,
      name: "Nike Football",
      slug: "nike-football",
      image: "/balls/nike-football.jpg",
      rating: 4.7,
      category: "football",
      price: 1999,
      desc: "Suitable For: All Conditions | Ideal For: Training/Match",
    },
     {
      id: 11,
      name: "Nivia Shinigstar",
      slug: "nivia-shinigstar",
      image: "/balls/nivia-shinigstar.jpg",
      rating: 4.8,
      category: "football",
      price: 975,
      desc: "32 panel stitched construction. Proudly made in India for Rough and Extreme palying conditions.",
    },
    {
      id: 12,
      name: "Nivia Engraver",
      slug: "nivia-engraver",
      image: "/balls/nivia-engraver.jpg",
      rating: 3.9,
      category: "basketball",
      price: 695,
      desc: "14 panel Moulded construction, Soft rubberized moulded material",
    },
  ],
  boardgames: [
     {
      id: 13,
      name: "Gisco Deluxe Chess Board",
      slug: "gisco-deluxe-chess-board",
      image: "/board/chessboard.jpg",
      rating: 4.3,
      category: "boardgames",
      price: 674,
      desc: "Conveniently foldable for easy transportation, this chess set includes a built-in storage compartment to securely house all 32 hand-carved chessmen, ensuring pieces are safe and contained when not in use.",
    },
    {
      id: 14,
      name: "GBC Magnetic Chess Set",
      slug: "gbc-magnetic-chess-set",
      image: "/board/chessboard2.jpg",
      rating: 4.3,
      category: "boardgames",
      price: 836,
      desc: "Plain box packing. With wooden magnetic coin 2.2'. 9'- 9x4.5x1.5 Inches.  12'-12x6x1.5 Inches"
    },
  ],
   racquets:[
       {
      id: 15,
      name: "Yonex Astrox Attack 9",
      slug: "yonex-astrox-attack-9",
      image: "/racquets/yonex.jpg",
      rating: 4.3,
      category: "racquets",
      price: 1398,
      desc: "Joint: Built-in T Joint , Head Shape: Isometric , Material: Graphite , Cover: Full Cover"
    },
     {
      id: 16,
      name: "Li-Ning AXForce 100",
      slug: "li-ning-aXForce-100",
      image: "/racquets/linung.jpg",
      rating: 4.1,
      category: "racquets",
      price: 6000,
      desc: "The Axforce 100 is built to maximise the impact of your attacks and gives complete & direct power transmission in every shot. The quality of heavy hits is very good, and there is minimal loss of tail speed"
    },
    ]
};

export default products;
