const products = {
  shoes: [
    {
      id: 1,
      name: "Nike Mercurial Superfly",
      slug: "nike-mercurial-superfly",
      image: "/nike-mercury.jpg",
      rating: 4.5,
      category: "football",
      price: 1999,
      desc: "High-performance football boots designed for explosive speed and precision control.",
    },
    {
      id: 2,
      name: "Air Jordan Legacy 312",
      slug: "air-jordan-legacy-312",
      image: "/air-jordan1.jpg",
      rating: 4.7,
      category: "basketball",
      price: 8999,
      desc: "Inspired by MJ's legacy, these basketball shoes offer ultimate grip and style on the court.",
    },
    {
      id: 3,
      name: "Nike LeBron Witness 7",
      slug: "nike-lebron-witness-7",
      image: "/nike-lebron1.jpg",
      rating: 4.3,
      category: "basketball",
      price: 4999,
      desc: "Built for explosive performance and durability, designed to support power players.",
    },
    {
      id: 4,
      name: "Strike 1912",
      slug: "Strike-1912",
      image: "/strike-1912-tennis.jpg",
      rating: 4.8,
      category: "tennis",
      price: 1999,
      desc: "Comfortable Tennis Badminton Sports Shoe For Men's",
    },
    {
      id: 5,
      name: "Boldfit Badminton Shoes",
      slug: "boldfit-badminton-shoes",
      image: "/boldfit-shuttle.jpg",
      rating: 4.5,
      category: "shuttle",
      price: 999,
      desc: "Breathable Non Marking Shoes for Badminton",
    },
    {
      id: 6,
      name: "Puma 22 FH",
      slug: "puma-22-fh",
      image: "/puma-cricket.jpg",
      rating: 4.6,
      category: "running",
      price: 4549.0,
      desc: "Experience unrivaled performance and style with Puma 22 FH Rubber VK Cricket Shoes",
    },
    {
      id: 7,
      name: "GEL-QUANTUM 360 VIII",
      slug: "gel-quantum-360-VIII",
      image: "/asics-volley.jpg",
      rating: 4.4,
      category: "volleyball",
      price: 11199,
      desc: "The GEL-QUANTUM 360™ VIII sneaker draws inspiration from super-natural forms and interlocking structures",
    },
    {
      id: 8,
      name: "Nike Air Zoom Structure 24",
      slug: "nike-air-zoom-structure-24",
      image: "/nike-air-zoom-structure-24.jpg",
      rating: 4.7,
      category: "running",
      price: 8199,
      desc: "Stability running shoes designed for controlled motion and reliable comfort.",
    },
  ],
  balls: [
    {
      id: 9,
      name: "Nivia Football",
      slug: "nivia-football",
      image: "/balls/nivia-football.jpg",
      rating: 4.7,
      category: "football",
      price: 999,
      desc: "Suitable For: All Conditions | Ideal For: Training/Match",
    },
     {
      id: 10,
      name: "Nike Football",
      slug: "nike-football",
      image: "/balls/nike-football.jpg",
      rating: 4.7,
      category: "football",
      price: 1999,
      desc: "Suitable For: All Conditions | Ideal For: Training/Match",
    },
  ],
};

export default products;
